def ask_personal():
    name=input("What is your name?\n>")
    age=input("How old are you?\n>")
    home_town=input("Where did you grow up\n>")
    food=input("What is your favorite food?\n>")
    hobby=input("What is your favorite hobby?\n>")
    print(name + "\n" + age + "\n" + home_town + "\n" + food + "\n" + hobby)
    print("--------------------------------------")
def school_pers():
    school_name=input("What is your school's name?\n>")
    grade=input("What grade are you in?\n>")
    subject=input("What is your favorite subject?\n>")
    hours=input("How many hours a week do you spend studying?\n>")
    grad_year=input("What is your grad year?\n>")
    print(school_name + "\n" + grade + "\n" + subject + "\n" + hours + "\n" + grad_year)
    print("--------------------------------------")
def goals_pers():
    job=input("What is your dream job?\n>")
    skill=input("What is one skill you want to learn?\n>")
    visit=input("What is one place you'd like to visit?\n>")
    goal=input("What is one personal goal you have?\n>")
    school_goal=input("What is one school goal you have?\n>")
    print(job + "\n" + skill + "\n" + visit + "\n" + goal + "\n" + school_goal)
ask_personal()
school_pers()
goals_pers()